name: rl_inventory
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  flutter_localizations:
    sdk: flutter
  flutter_nfc_kit: ^3.5.2
  async: ^2.11.0
  characters: ^1.3.0
  clock: ^1.1.1
  collection: ^1.18.0
  http_parser: ^4.0.2
  material_color_utilities: ^0.11.1
  meta: ^1.15.0
  path: ^1.9.0
  string_scanner: ^1.2.0
  analyzer: ^6.7.0
  boolean_selector: ^2.1.1
  fake_async: ^1.3.1
  leak_tracker: ^10.0.5
  leak_tracker_flutter_testing: ^3.0.5
  matcher: ^0.12.16+1
  shelf: ^1.4.1
  stack_trace: ^1.11.1
  test_api: ^0.7.2
  vm_service: ^14.2.5
  _fe_analyzer_shared: ^72.0.0
  flutter_local_notifications: ^18.0.0
  local_auth: ^2.3.0
  flutter_colorpicker: ^1.1.0
  flutter_bluetooth_serial:
    git:
      url: https://github.com/edufolly/flutter_bluetooth_serial.git
      ref: master

  provider: ^6.1.2
  
dev_dependencies:
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true # Permette di generare file per la localizzazione


